# Core IPC Pipe Socket Engine
input-ipc-server=/tmp/mpvsocket

# Force mpv to parse the full playlist array
# yes-playlist=yes

# Use the rock-solid static text cookie file
ytdl-raw-options=cookies=/home/robin/.config/yt-dlp/youtube-cookies.txt
